substitutions:
  device_name: ble-ip101-wifi-bridge
  friendly_name: BLE Proxy IP101 Wi-Fi Bridge

packages:
  core: !include ../packages/bridge-core.yaml
  network: !include ../packages/bridge-network-wifi.yaml

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf

esphome:
  build_path: build/ip101-wifi-bridge
