esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO33
      inverted: true
    name: Reset Button

output:
  - platform: gpio
    pin: GPIO14
    inverted: true
    id: power_led
  - platform: gpio
    pin: GPIO12
    inverted: true
    id: bluetooth_led

i2c:
  sda: GPIO15
  scl: GPIO13
  scan: false
